var Worldmap2d_pl = {
    errorloadingmodel: 'Nie udało się załadować modelu.',
    modelnotfound: 'Model nie został znaleziony.',
    no_model: 'Brak dostępnego modelu dla tego budynku.',
    no_grounddata: 'Brak danych adresowych dla tego budynku.',
    value: 'Wartość',
    datafrom: 'Dane z dnia',
    setid: 'Numer zestawu danych',
    lat: 'Szerokość geograficzna',
    lon: 'Długość geograficzna',
    height: 'Wysokość',
    model_add: 'Dodaj model',
    model_url: 'URL do modelu',
    model_typeunknown: 'Nie rozpoznano typu pliku',
    model_typechoose: 'Proszę wybrać odpowiedni typ pliku:',
    model_typeselect: 'Proszę wybrać typ',
    fileurl_error: 'Nie udało się pobrać pliku.',
    fileurl_html: 'Plik wydaje się być stroną HTML, a nie plikiem danych. Kliknij <a href="%url%" target="_blank">tutaj</a>, aby odwiedzić stronę.',
    model_selectsubmodel: 'Wybierz submodel',
    model_subchoose: 'Podana zasób zawiera więcej niż jeden model. Proszę wybrać wszystkie, które mają być wyświetlone.',
    model_subselectbtn: 'Wyświetl wybrane',
    model_subsseperate: 'Wyświetl submodele jako osobne warstwy',
    geojson_featuresmissing: 'Otrzymane dane nie są prawidłowym geoJSON. Brakuje obiektu >features<.',
    wms_tileerror: 'Co najmniej jeden kafelek nie został załadowany. Kliknij <a href="%url%" target="_blank">tutaj</a>, aby zobaczyć komunikat błędu serwera WMS.',
    wms_baseurlentered: 'Podano podstawowy URL WMS. Istniejące warstwy nie mogły zostać automatycznie wykryte. Proszę podać warstwy do wyświetlenia (lista rozdzielona przecinkami).',
    context_copycoords: 'Kopiuj współrzędne',
    context_centermap: 'Wycentruj mapę tutaj',
    context_zoomin: 'Powiększ',
    context_zoomout: 'Pomniejsz'
};
export default Worldmap2d_pl;