var Charts_Datafilterbar_en = {
    menu: 'Filter and settings',
    availrange: 'Available time range',
    filters: 'Filters',
    target: 'Apply to',
    target_both: 'Chart and table',
    target_chart: 'Chart only',
    target_table: 'Table only',
    timerange: 'Time range',
    value: 'Value',
    attr: 'Attribute',
    apply: 'Apply',
    reset: 'Reset',
    aggregation: 'Aggregation',
    unit_seconds: 'Seconds',
    unit_minutes: 'Minutes',
    unit_hours: 'Hours',
    unit_days: 'Days',
    series: 'Data series',
    computed: 'Computed column',
    formula: 'Formula',
    insertattr: 'Insert',
    formulaerror: 'The formula contains unsupported values.',
    formulahint: 'Insert attributes using the selection.',
    mathliveerror: 'MathLive could not be loaded.',
    addcolumn: 'Add column to table',
    datasource: 'Datasource',
    adaptation: 'Data adaptation',
    adaptation_auto: 'Automatic',
    adaptation_deterministic: 'Rule based',
    adaptation_ai: 'Use AI',
    loadsource: 'Load',
    removesource: 'Remove',
    tableexport: 'Table export',
    exportformat: 'Format',
    exportformat_csv: 'CSV',
    exportformat_json: 'JSON',
    exportformat_xlsx: 'XLSX',
    tableexportbtn: 'Export table',
    tableexportempty: 'No table data is available for export.',
    settings: 'Settings',
    settingshint: 'Current page settings can be saved and reused here.',
    settingstxt: 'Download settings JSON',
    settingscopy: 'Copy settings JSON',
    settingscopied: 'JSON copied.',
    settingscopydone: 'Copied',
    settingscopyfailed: 'JSON could not be copied.',
    importbtn: 'Import settings',
    settingsinvalid: 'The selected file does not contain valid JSON.',
    settingsreaderror: 'The selected file could not be read.',
    requestor: 'Resulting dataRequestor',
    requestorurl: 'Request URL',
    renameprompt: 'New column name'
};
export default Charts_Datafilterbar_en;
