var ExplainComponents_de = {
    noComponentSelected: 'Nie wybrano komponentu do opisania.',
    noDescription: 'Ten komponent nie posiada opisu.',
    datasets: 'Wymagania dotyczące zestawów danych',
    attributeName: 'Nazwa',
    attributeDesc: 'Opis',
    attributeReq: 'Wymagane',
    attributesNone: 'Ten komponent nie wymaga atrybutów w danych.',
    functions: 'Funkcje',
    noFunctions: 'Ten komponent nie udostępnia funkcji do użytku zewnętrznego.',
    noParams: 'Ta metoda nie posiada parametrów',
    paramName: 'Nazwa parametru',
    paramType: 'Typ parametru',
    paramDesc: 'Opis',
    noReturn: 'Brak wartości zwrotnej',
    returnType: 'Typ zwracany',
    returnDesc: 'Opis wartości zwrotnej',
    templates: 'Dostępne szablony',
    template: 'Wymagania dotyczące szablonów',
    tplsNone: 'Ten komponent nie posiada szablonów.',
    tmplelemSelector: 'Selektor CSS',
    tmplelemDesc: 'Opis',
    tmplelemReq: 'Wymagane',
    tmplelemsNone: 'Ten komponent nie stawia wymagań wobec szablonu.',
    styles: 'Style',
    styleSelector: 'Selektor CSS aktywujący styl.',
    styleDesc: 'Opis',
    stylesNone: 'Ten komponent nie udostępnia stylów.',
    dependencies: 'Zależności',
    dependenciesName: 'Nazwa',
    dependenciesDesc: 'Opis',
    dependenciesPath: 'Ścieżka',
    dependenciesNone: 'Ten komponent nie posiada zależności.',
    options: 'Opcje',
    optionsNone: 'Ten komponent nie posiada opcji.',
    optionsName: 'Nazwa',
    optionsDesc: 'Opis',
    optionsNodesc: 'Ta opcja nie została udokumentowana',
    optionsDefault: 'Wartość domyślna',
    optionsExample: 'Przykład',
    optionsNoExample: 'Brak dostępnego przykładu',
    plugins: 'Wtyczki',
    pluginsNone: 'Ten komponent nie posiada wtyczek',
    params: 'Parametry i zwracane wartości',
    events: 'Zdarzenia',
    eventsdesc: 'Poniżej znajdują się zdarzenia, które mogą być wywoływane przez ten komponent. Każde zdarzenie to JS CustomEvent, a dane są przekazywane w atrybucie "detail". REQUESTOR_Id należy zastąpić identyfikatorem elementu swa.'
};
export default ExplainComponents_de;