var Edit_pl = {
    noinputdef: 'Nie można wygenerować formularza wejściowego. Nie podano definicji wejścia.',
    errorcreateform: 'Błąd podczas tworzenia formularza.',
    errorgetoptions: 'Błąd podczas pobierania opcji wyboru.',
    forgotteninput: 'Nie wypełniono wszystkich wymaganych pól lub występują nieprawidłowe dane.',
    noObjectTemplates: 'Nie zdefiniowano możliwych wpisów.',
    formlegend: 'Edytuj zestaw danych',
    adddataset: 'Dodaj',
    addsavefirst: 'Najpierw zapisz ostatnio dodany zestaw danych.',
    loadingeditform: 'Ładowanie formularza edycji',
    editor: 'Edytor',
    newdataset: 'Nowy zestaw danych',
    editdataset: 'Edytuj zestaw danych',
    valuerequired: 'Proszę podać wartość dla %attrname%.',
    noselection: 'Brak wyboru',
    drophere: 'Przeciągnij tutaj',
    dropNotAccepted: 'Ten element nie może zostać tutaj przypisany.',
    dropFetchError: 'Nie udało się pobrać danych elementu.',
    couldnotsave: 'Nie można zapisać danych wejściowych.',
    refDelete: 'Usuń połączenie',
    save: 'Zapisz',
    saved: 'Dane zostały zapisane.',
    delchild: 'Usuń',
    filesourcenotsupported: 'Ta funkcja nie jest dostępna dla danych załadowanych z plików.',
    groupeditbtn: 'Edycja grupowa',
    groupedit: 'Edycja grupowa – zmiana wartości spowoduje aktualizację tej właściwości we wszystkich powiązanych polach.',
    autodata_start: 'Rozpocznij automatyczną aktualizację danych',
    autodata_stop: 'Zatrzymaj automatyczną aktualizację danych',
    autodata_requestor_err: 'Nie udało się pobrać danych.',
    autodata_script_err: 'Nie udało się przetworzyć danych.',
    autodata_requestor_nodata: 'Brak dostępnych danych.'
};
export default Edit_pl;