var Worldmap2d_RouteAnalytics_en = {
    menu: 'Filter and settings',
    menu_title: 'Route filter',
    filters: 'Filters',
    available_range: 'Available time range',
    range_separator: ' to ',
    time_range: 'Time range',
    aggregation: 'Aggregation',
    target: 'Apply to',
    target_both: 'Map and table',
    target_map: 'Map only',
    target_table: 'Table only',
    seconds: 'Seconds',
    minutes: 'Minutes',
    hours: 'Hours',
    days: 'Days',
    route: 'Route',
    all_routes: 'All routes',
    attribute: 'Attribute',
    no_attribute: 'No attribute filter',
    value: 'Value',
    health: 'Health',
    all_health: 'All ratings',
    health_good: 'Good',
    health_medium: 'Medium',
    health_bad: 'Bad',
    health_unknown: 'Unknown',
    apply: 'Apply',
    reset: 'Reset',
    tableexport: 'Table export',
    exportformat: 'Format',
    exportformat_csv: 'CSV',
    exportformat_json: 'JSON',
    exportformat_xlsx: 'XLSX',
    tableexportbtn: 'Export table',
    tableexportempty: 'No table data is available for export.',
    rename_column: 'Rename column',
    rename_prompt: 'New column name',
    summary_title: 'Routes',
    healthiest_route: 'Healthiest route',
    no_routes: 'No matching routes found.',
    points: 'Points',
    start: 'Start',
    duration: 'Duration',
    distance: 'Distance',
    elevation_gain: 'Elevation gain',
    visible: 'Visible',
    routes_visible: 'routes visible',
    average: 'Average',
    route_prefix: 'Route',
    unnamed_route: 'Unnamed route',
    unrouted_points: 'Values without route',
    route_layer: 'Routes',
    search: 'Search routes',
    toggle_all_routes: 'Toggle all routes',
    yes: 'yes',
    no: 'no',
    not_available: 'n/a'
};

export default Worldmap2d_RouteAnalytics_en;
