/* 
 * Language file for SWAC internationalization
 */
let core_pl = {
    waitingbackend: 'Aplikacja jest uruchamiana, proszę o chwilę cierpliwości.',
    sourceerror: 'Źródło danych %source% jest niedostępne. Sprawdź konfigurację.',
    loaderror: 'Nie udało się załadować aplikacji. Kliknij OK, aby spróbować ponownie.',
    loadingdata: 'Ładowanie danych',
    loadingtemplate: 'Ładowanie widoku',
    showWhenNoData: 'True powoduje wyświetlenie komponentu nawet bez danych',
    model_nodata: 'Brak dostępnych danych',
    model_savesuccsess: 'Dane zostały zapisane.',
    model_saveerror: 'Nie udało się zapisać danych.',
    remote_backenderror: 'Przepraszamy. Wystąpił błąd.',
    save: 'Zapisz',
    saveall: 'Zapisz wszystko',
    savetofileerr: 'Zmiany w zestawach danych załadowanych z plików statycznych nie mogą zostać zapisane.',
    delete: 'Usuń',
    moreerrors: 'Wystąpiło jeszcze %number% błędów.',
    sortChildsSorting: 'Dane od %requestor_id% są sortowane.',
    savesuccsess: 'Zapis zakończony pomyślnie',
    saveerror: 'Błąd podczas zapisywania',
    updatesuccsess: 'Aktualizacja zakończona pomyślnie',
    updateerror: 'Błąd podczas aktualizacji',
    deletesuccsess: 'Zestaw danych został usunięty',
    deleteerror: 'Błąd podczas usuwania',
    appOffline_title: 'Funkcja niedostępna offline',
    appOffline_pagedesc: 'Ta funkcja nie jest dostępna offline. Połącz się z Internetem, aby z niej skorzystać.',
    appOffline: 'Jesteś offline. Połącz się z siecią, aby kontynuować.',
    appOfflineProgressive: 'Pracujesz offline. Dane zostaną zsynchronizowane po nawiązaniu połączenia.',
    appUnreachable: 'Aplikacja sieciowa jest niedostępna. Poczekaj, aż usługa będzie ponownie dostępna.',
    appUnreachableProgressive: 'Aplikacja sieciowa jest niedostępna. Dane zostaną zsynchronizowane, gdy usługa będzie dostępna.',
    loadFailLogin: 'Musisz być zalogowany, aby zobaczyć tę zawartość.',
    loadFailRight: 'Nie masz uprawnień do przeglądania tej zawartości.',
    loadFailErr: 'Wystąpił błąd podczas ładowania danych z >%source%<.',
    day_0: 'Nd',
    day_1: 'Pn',
    day_2: 'Wt',
    day_3: 'Śr',
    day_4: 'Cz',
    day_5: 'Pt',
    day_6: 'Sb',
    view_adddata: 'Dodaj dane',
    contenttype_unsupported: 'Typ zawartości %content-type% nie jest obecnie obsługiwany.',
    contenttype_jparseerr: 'Nie udało się przetworzyć zawartości jako JSON.',
    updateavail: 'Dostępna jest aktualizacja. Uruchom ponownie aplikację, aby ją zainstalować.'
};
export default core_pl;