var Mediaplayer_pl = {
    playlist: 'Lista odtwarzania',
    fullscreen: 'Tryb pełnoekranowy',
    play: 'Odtwórz',
    pause: 'Pauza',
    prevtitle: 'Poprzedni utwór',
    nexttitle: 'Następny utwór',
    volume: 'Głośność',
    mute: 'Wycisz',
    download: 'Pobierz bieżące medium',
    sendcomment: 'Wyślij komentarz',
    closeoverlay: 'Kontynuuj',
    remove: 'Usuń z listy odtwarzania',
    save: 'Zapisz listę odtwarzania',
    titlepage: 'Więcej o utworze',
    title: 'Tytuł',
    title_download: 'Pobierz ten utwór',
    artist: 'Artysta',
    album: 'Album',
    license: 'Licencja',
    info: 'Informacje',
    time: 'Czas odtwarzania utworu / listy',
    title_problem: 'Ten utwór jest obecnie niedostępny.',
    title_none: 'Brak dostępnych utworów.',
    anounce: 'Następnie usłyszysz %title% wykonany przez %artist%',
    makeoffline: 'Udostępnij listę odtwarzania offline',
    playnotallowed: 'Przeglądarka zablokowała odtwarzanie za pomocą klawisza. Kliknij OK, a następnie naciśnij spację, aby rozpocząć odtwarzanie.'
};
export default Mediaplayer_pl;